[language-server.gopls.config]
gofumpt = true

# [language-server.golangci-lint-lsp]
# command = 'golangci-lint-langserver'

# [language-server.golangci-lint-lsp.config]
# command = ['golangci-lint', 'run', '--out-format', 'json', '--issues-exit-code=1']

[[language]]
name = 'go'
language-servers = ['gopls']

[[language]]
name = 'toml'
formatter = { command = 'taplo', args = ['format', '-', '-o', 'column_width=160'] }
auto-format = true

[[language]]
name = 'sql'
formatter = { command = 'sqlformat', args = ['--reindent', '--indent_width', '2', '--keywords', 'upper', '--identifiers', 'lower', '-'] }
auto-format = true

[[language]]
name = 'bash'
indent = { tab-width = 4, unit = '    ' }
formatter = { command = 'shfmt', args = ['-i', '4'] }
auto-format = true

[[language]]
name = 'python'
formatter = { command = 'black', args = ['--quiet', '-'] }
auto-format = true

[[language]]
name = 'html'
formatter = { command = 'prettier', args = ['--parser', 'html'] }

[[language]]
name = 'css'
formatter = { command = 'prettier', args = ['--parser', 'css'] }

[[language]]
name = 'json'
formatter = { command = 'deno', args = ['fmt', '-', '--ext', 'json', '--line-width', '160'] }

[[language]]
name = 'markdown'
formatter = { command = 'deno', args = ['fmt', '-', '--ext', 'md', '--line-width', '160'] }
auto-format = true

[[language]]
name = 'typescript'
formatter = { command = 'deno', args = ['fmt', '-', '--ext', 'ts', '--line-width', '160'] }
auto-format = true

[[language]]
name = 'javascript'
formatter = { command = 'deno', args = ['fmt', '-', '--ext', 'js', '--line-width', '160'] }
auto-format = true

[[language]]
name = 'jsx'
formatter = { command = 'deno', args = ['fmt', '-', '--ext', 'jsx', '--line-width', '160'] }
auto-format = true

[[language]]
name = 'tsx'
formatter = { command = 'deno', args = ['fmt', '-', '--ext', 'tsx', '--line-width', '160'] }
auto-format = true
